spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/mem:db;MODE=MYSQL
    username: weolbu
    password: weolbu5678

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create # 운영 환경에서 validate로 변경 필요
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    header: Authorization
    secret: 394763e7b962d3dbb8367630e7b9e7fa02a5ad01da0387f4f68c0df9f052de83
    access-token-validity-in-seconds : 7200
    refresh-token-validity-in-seconds : 86400

  security:
    password:
      salt: A!206@LET3S-SSA%8TAL@

logging.level:
  org.hibernate.SQL: debug

aes:
  secret-key: A5d_s3$:Q!EK]e6#Up'HNdK(`?7WhE`L

app:
  data-initializer:
    enabled: true